config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'welcome#home'
get 'home', to: 'welcome#home'
get 'about', to: 'welcome#about'
get 'contact', to: 'welcome#contact'
resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum:300}
    validates :user_id, presence: true # enforce to have user_id present
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles # for one to many association
    before_save { self.email = email.downcase } # to save email in downcase 
    validates   :username, presence: true,
                uniqueness: { case_sensitive: false },
                length:{ minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates   :email, presence: true, length: { maximum: 105},
                uniqueness: {case_sensitive: false},
                format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	def index
		@articles= Article.all
	end

	def new
		@article = Article.new
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:success] = "Article is successfully deleted"
			redirect_to article_path(@article)
		else
			render 'new'
		end
		#@article.save
	end

	def show

		

	end

	def destroy
		
		@article.destroy
		flash[:danger] = "Article is successfully deleted"
		redirect_to articles_path
	end

	def edit
		
	end

	def update
		
		if @article.update(article_params)
			flash[:success] = "Article is successfully deleted"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	private
		def article_params
			params.require(:article).permit(:title, :description)
		end

		def set_article
			@article=Article.find(params[:id])
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home
		
	end

	def about

	end

	def contact

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<!--<div clas="col-sm-2 control-label">-->
				<%= f.label :title,class: "col-sm-2 control-label" %>
			<!--</div>-->
			<div class="col-sm-8">
				<%= f.text_field :title,class: "form-control", placeholder: "Title for article", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<!--<div clas="col-sm-2 control-label">-->
				<%= f.label :description,class: "col-sm-2 control-label" %>
			<!--</div>-->
			<div class="col-sm-8">
				<%= f.text_area :description, rows: 10 ,class: "form-control", placeholder: "Description for article" %>
			</div>
		</div>
		<div class="form-group">
    		<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: "btn btn-default" %>
			</div>
		</div>
		<div class="col-xs-4 col-xs-offset-4">
			<%= link_to "Cancel request and return to article listing", articles_path %>
		</div>
	</div>
</div>

<% end %>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title"> 
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, length: 100) %>
				</div>
				<div class="article-actions">
					<%= link_to "Edit this article", edit_article_path(article),class: "btn btn-xs btn-primary" %>
					<%= link_to "Delete this article", article_path(article), method: :delete, 
														data: {confirm: "Are you sure ?"}, 
														class: "btn btn-xs btn-danger" %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">Create a article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">
	Title: <%= @article.title %>
</h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center description"><strong>Description:</strong></h4>
	<hr><%= simple_format(@article.description) %>
	<div class="article-actions">
		<%= link_to "Edit this article", edit_article_path(@article),class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete this article", article_path(@article), method: :delete, 
											data: {confirm: "Are you sure ?"}, 
											class: "btn btn-xs btn-danger" %>
		<%= link_to "Back to article listing", articles_path, class: "btn btn-xs btn-success" %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="footer">
	<small>
		Copywrite &copy; <a href="#">The Rails Projects</a>
	</small>
	<nav>
		<ul>
			<li>
				<%= link_to "About", about_path %>
			</li>
		</ul>
	</nav>
	</div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name,msg| %>
		<div class='alert alert-<%="#{name}"%>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div,msg, :id => "flash_#{name}" if msg.is_a?(String)%>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails Projects", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Article", articles_path  %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjects</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
						Prohibited this article from being saved:
				</h2>
				<div class="panel-body">
					<ul>
						<%= obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/welcome/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Home', root_path %>

app/views/welcome/contact.html.erb
<h1>This is Contact Page</h1>
<br>
<%= link_to"Home", home_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Rails Projects</h1>
  <%= link_to "Sign Up Now" , "#" , class: "btn btn-danger btn-lg btn-xlarge" %>
</div>
<%= link_to 'About', about_path %><br>
<%=link_to 'New', new_article_path %>